### ISSUE TITLE
42 :-)

### ISSUE THREAD

**Issue by naartjie** [nuclearace/Socket.IO-Client-Swift#14]
What is the meaning of the special value `"42"` in [SocketIOClient.swift](https://github.com/nuclearace/Socket.IO-Client-Swift/blob/44de79d8c58a60bd6e0aaa72d21e88e0ac515395/SwiftIO/SocketIOClient.swift#L516), and likewise `"43"` `"45"` and `"46"` in the same file.

The [`==` comparison in `master`](https://github.com/nuclearace/Socket.IO-Client-Swift/blob/6e8a32361c0ac3fa49d564582c05acc1ee17a1d8/SwiftIO/SocketIOClient.swift#L389) has changed to [`hasPrefix("42")`](https://github.com/nuclearace/Socket.IO-Client-Swift/blob/44de79d8c58a60bd6e0aaa72d21e88e0ac515395/SwiftIO/SocketIOClient.swift#L516) in `1.2` branch.

Which could be the reason for me not receiving messages/events from the server. Should this change be merged into `master`?

**Comment by nuclearace** [comment]
It has to with the socket.io protocol. https://github.com/Automattic/socket.io-protocol

42 - event
45 - binary event
43 - ack
46 - binary ack

If you're not receiving an event in the master branch, it's probably because the server is sending an id with the event. Which signals it wants an ack. The master branch doesn't properly parse these.

I might see about backporting the new stuff from 1.2.

**Comment by nuclearace** [comment]
Hopefully didn't break everything.

**Comment by naartjie** [comment]
I don't see any reference to `42..46` in the docs, I only see the `0..6` for packet type. I guess the '42' must be composed from smaller parts, but I can't figure out where that is specified. Anyways, thanks for your help, I guess in my setup I had callbacks in the server expecting an ACK and nothing in the client to support that.

Thanks for merging ACK's into `master` :+1:
