### ISSUE TITLE
Suggestion: let some more people know about this project

### ISSUE THREAD

**Issue by naartjie** [nuclearace/Socket.IO-Client-Swift#25]
I have been using this lib in a beta version of our product. I know it's still very early days, but based on my experience, compared to other alternatives I feel this is by far the best option out there (for socket.io 1.0+ and iOS 7 and up obviously).

@nuclearace you know @rauchg, or at least have an online rapport with him. I see that the [Socket.IO FAQ](http://socket.io/docs/faq/) only mentions [SIOSocket](https://github.com/MegaBits/SIOSocket), and I feel like this project should definitely be up there as options for iOS. 

Thoughts?

**Comment by nuclearace** [comment]
Well we did do http://socket.io/blog/socket-io-on-ios/

I can ask him to add it the list though.

**Comment by naartjie** [comment]
Very cool, I haven't seen that blog post yet, thanks for sharing.

**Comment by markschmid** [comment]
I agree with @naartjie . We have looked at all alternatives we could find, but this is the best option. SIOSocket cannot keep up performancewise (possibly because it does this JS evaluation "magic", see https://medium.com/@ryAn_Hdot/real-time-environments-f3fdc961581 ) and other libraries are not up to date with socket.io 1.0+ (and also their interface is less convenient).
It should definitely be mentioned in the FAQ as an option for iOS.
